[build-system]

[project]
name = "PackY"
version = "0.9.0.0"
authors = [
  {name = "Marie-Neige Chapel", email = ""},
  {name = "Joseph Garnier", email = ""},
]
maintainers = [
  {name = "Marie-Neige Chapel", email = ""},
  {name = "Joseph Garnier", email = ""},
]
description = "PackY is a simple and intuitive software for creating batch file archives."
readme = "README.md"
license = "GPL-3.0"
license-files = ["LICENSE.md"]
keywords = ["pyside", "zip", "packager", "archive"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Topic :: Desktop Environment :: File Managers",
  "Programming Language :: Python :: 3.14",
  "Private :: Do Not Upload",
]
dependencies = [
  "pyside6==6.11.0",
  "pyyaml==6.0.3",
  "jsonschema==4.26.0",
  "pytest==9.0.3",
  "pytest-mock==3.15.1",
  "pytest-qt==4.5.0",
]
requires-python = ">= 3.14.3"

[project.optional-dependencies]
tests = [
  "pytest==9.0.3",
  "pytest-mock==3.15.1",
  "pytest-qt==4.5.0",
]

[project.urls]
Homepage = "https://github.com/mnchapel/packy"
Documentation = "https://github.com/mnchapel/packy"
Repository = "https://github.com/mnchapel/packy"
"Bug Tracker" = "https://github.com/mnchapel/packy/issues"
Changelog = "https://github.com/mnchapel/packy/CHANGELOG.md"

[tool.distutils.build_exe]
includes = ["constants", "core", "models", "task", "ui", "utils", "views", "widgets"]
excludes = ["tkinter", "unittest"]
include_files = ["resources"]

[tool.pyright]
typeCheckingMode = "strict"

[tool.pytest]
addopts = [
  "-vvv",
  "-ra",
  "--import-mode=importlib",
  "--strict-markers",
  "--qt-log-format=[{rec.when:%Y-%m-%dT%H:%M:%S.%f}][{rec.context.file}:{rec.context.line}][{rec.log_type_name}]: {rec.message}",
]
cache_dir= "tests/.pytest_cache"
console_output_style = "classic"
minversion = "9.0.3"
pythonpath = ["."]
testpaths = ["tests"]
norecursedirs = ["data"]
markers = [
  "scenario_happy_path: TODO",
  "scenario_alternate_path: TODO",
  "scenario_invalid_input: TODO",
  "scenario_failure_error_path: TODO",
  "technique_equivalence_partitioning: TODO",
  "technique_boundary_value_analysis: TODO",
  "technique_decision_table: TODO",
  "technique_state_transition: TODO",
  "technique_branch: TODO",
  "technique_error_guessing: TODO",
]
# Note: Console and file logging are enabled only in debug mode, via VS Code's 'launch.json'.
log_level = "DEBUG"
log_date_format = "%Y-%m-%dT%H:%M:%S.%f%:z"
log_format = "[%(asctime)s][%(process)d,0x%(thread)x][%(pathname)s:%(lineno)d][%(levelname)s]: %(message)s"
log_file_mode = "w"
required_plugins = ["pytest-qt>=4.5.0"]

[tool.pyside6-project]
# The list of options can be seen with the command `pyside6-project --help` and on the page <https://doc.qt.io/qtforpython-6/tools/pyside-project.html>
files = [
  # WARNING! This list is auto updated by the just build helper
  "i18n/.gitignore",
  "i18n/translations.txt",
  "main.py",
  "packy/.gitignore",
  "packy/constants/__init__.py",
  "packy/constants/file_filters.py",
  "packy/constants/settings_keys.py",
  "packy/constants/ui_strings.py",
  "packy/core/__init__.py",
  "packy/core/app.py",
  "packy/core/app_config.py",
  "packy/core/archiver.py",
  "packy/core/archiver_config_model.py",
  "packy/core/archiver_config_panel.py",
  "packy/core/batch.py",
  "packy/core/batch_workspace.py",
  "packy/core/batch_workspace_dialogs.py",
  "packy/core/batch_workspace_history.py",
  "packy/core/configurable.py",
  "packy/core/localization.py",
  "packy/core/logger.py",
  "packy/core/user_settings.py",
  "packy/graveyard/external_data_access.py",
  "packy/graveyard/files_model.py",
  "packy/graveyard/old_test_files_model.py",
  "packy/graveyard/old_test_packer.py",
  "packy/graveyard/old_test_zip_packer.py",
  "packy/graveyard/packer.py",
  "packy/graveyard/packer_factory.py",
  "packy/graveyard/progression.py",
  "packy/graveyard/session.py",
  "packy/graveyard/session_decoder.py",
  "packy/graveyard/session_encoder.py",
  "packy/graveyard/task_list_model.py",
  "packy/graveyard/task_model.py",
  "packy/graveyard/tree_view_proxy_model.py",
  "packy/graveyard/warnings.py",
  "packy/graveyard/zip_packer.py",
  "packy/ui/__init__.py",
  "packy/ui/about_dialog.py",
  "packy/ui/about_dialog.ui",
  "packy/ui/fix_warnings.py",
  "packy/ui/fix_warnings.ui",
  "packy/ui/main_window.py",
  "packy/ui/main_window.ui",
  "packy/ui/options_dialog.py",
  "packy/ui/options_dialog.ui",
  "packy/ui/ui_about_dialog.py",
  "packy/ui/ui_fix_warnings.py",
  "packy/ui/ui_main_window.py",
  "packy/ui/ui_options_dialog.py",
  "packy/utils/__init__.py",
  "packy/utils/int_str_enum.py",
  "packy/utils/translation.py",
  "packy/widgets/__init__.py",
  "packy/widgets/formatted_log_widget.py",
  "packy/widgets/radio_group_widget.py",
  "resources/packy.qrc",
]

[tool.pyside6-uic]
# The list of options can be seen with the command `pyside6-uic --help-all` and on the page <https://doc.qt.io/qt-6/uic.html>
options = [
  "--absolute-imports",
]

[tool.pyside6-rcc]
# The list of options can be seen with the command `pyside6-rcc --help-all` and on the page <https://doc.qt.io/qt-6/rcc.html>
options = [
  "-compress-algo",
  "zlib",
]
