indent-width = 4
line-length = 100

[lint]
select = ["ALL"]
ignore = [
  "EM101", # raw-string-in-exception
]
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint.pydocstyle]
convention = "google"

[lint.isort]
section-order = ["local-folder", "first-party", "third-party", "standard-library", "future"]
known-local-folder = ["packy", "models", "ui", "utils", "views"]
known-first-party = ["packy", "models", "ui", "utils", "views"]

[lint.isort.import-heading]
local-folder = "Local application"
first-party = "Local application"
third-party = "Third-party"
standard-library = "Standard library"
future = "Future library"